### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by xinyijun** [ontio/ontology-go-sdk#24]
When use ontology-go-sdk, errors below are reported, we need to delete vendor/github.com/ontio/ontology/vendor/github.com/ontio/ontology-crypto to build successfully.

vendor/github.com/ontio/ontology-go-sdk/common/common.go:71:10: cannot use []"company/project/repo/vendor/github.com/ontio/ontology-crypto/keypair".PublicKey literal (type []"company/project/repo/vendor/github.com/ontio/ontology-crypto/keypair".PublicKey) as type []"company/project/repo/vendor/github.com/ontio/ontology/vendor/github.com/ontio/ontology-crypto/keypair".PublicKey in field value
vendor/github.com/ontio/ontology-go-sdk/common/common.go:97:46: cannot use pubKeys (type []"company/project/repo/vendor/github.com/ontio/ontology-crypto/keypair".PublicKey) as type []"company/project/repo/vendor/github.com/ontio/ontology/vendor/github.com/ontio/ontology-crypto/keypair".PublicKey in argument to types.AddressFromMultiPubKeys
vendor/github.com/ontio/ontology-go-sdk/common/common.go:113:23: cannot use sigs.PubKeys (type []"company/project/repo/vendor/github.com/ontio/ontology/vendor/github.com/ontio/ontology-crypto/keypair".PublicKey) as type []"company/project/repo/vendor/github.com/ontio/ontology-crypto/keypair".PublicKey in argument to pubKeysEqual
vendor/github.com/ontio/ontology-go-sdk/common/common.go:125:11: cannot use pubKeys (type []"company/project/repo/vendor/github.com/ontio/ontology-crypto/keypair".PublicKey) as type []"company/project/repo/vendor/github.com/ontio/ontology/vendor/github.com/ontio/ontology-crypto/keypair".PublicKey in field value
vendor/github.com/ontio/ontology-go-sdk/common/common.go:171:27: cannot use signer.SigScheme (type "company/project/repo/vendor/github.com/ontio/ontology/vendor/github.com/ontio/ontology-crypto/signature".SignatureScheme) as type "company/project/repo/vendor/github.com/ontio/ontology-crypto/signature".SignatureScheme in argument to "company/project/repo/vendor/github.com/ontio/ontology-crypto/signature".Sign

**Comment by gasby88** [comment]
Remove ontology-crypto in github.com/ontio/ontology/vendor, and put it to github.com/ontio

**Comment by xinyijun** [comment]
It was managed by glide, I didn't touch it, could we solve it at the first place?
