### ISSUE TITLE
go sdk

### ISSUE THREAD

**Issue by hongyuefan** [ontio/ontology-go-sdk#5]
when use ontology-go-sdk package 

rpc.go:37:2: cannot find package "github.com/ontio/ontology/smartcontract/service/wasm" in any of:
	/usr/lib/golang/src/github.com/ontio/ontology/smartcontract/service/wasm (from $GOROOT)
	/root/gocode/src/github.com/ontio/ontology/smartcontract/service/wasm (from $GOPATH)
../utils/utils.go:28:2: cannot find package "github.com/ontio/ontology/vm/types" in any of:
	/usr/lib/golang/src/github.com/ontio/ontology/vm/types (from $GOROOT)
	/root/gocode/src/github.com/ontio/ontology/vm/types (from $GOPATH)

**Comment by gasby88** [comment]
Have already fix,  Please use the latest version.
